name: Deploy to GitHub Packages

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  on-success:
    name: Deploy to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: packages
          path: build_output/
      - name: Tmp
        run: 'echo "Publish Nightly"'